<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastLimited()
    {
        $articles = $this->createQueryBuilder('a')
            ->addOrderBy('a.id', 'desc')
            ->setMaxResults( 5 )
            ->getQuery()
            ->getResult()
        ;
        return $articles;
    }


    public function getMostPopular()
    {
        $articles = $this->createQueryBuilder('a')
            ->addSelect('count(a.id) as HIDDEN nb_a')
            ->leftJoin('a.basket_users', 'u')
            ->groupBy('a')
            ->addOrderBy('nb_a', 'desc')
            ->setMaxResults( 3 )
            ->getQuery()->getResult();
        ;
        return $articles;
    }

}
