<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastLimited()
    {
        $articles = $this->createQueryBuilder('a')
            ->addOrderBy('a.id', 'desc')
            ->setMaxResults( 5 )
            ->getQuery()
            ->getResult()
        ;

        return $articles;
    }
}
