<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
    public function findTransaction(User $user)
    {
        $articles = $this->createQueryBuilder('a')
            ->where('a.user_buy = :user')
            ->orWhere('a.user_sale = :user')
            ->setParameter('user', $user)
            ->orderBy('a.date', 'ASC')
            ->getQuery()
            ->getResult();

        return $articles;
    }
}
