framework:
    csrf_protection: ~


security:

    providers:
        pokeshop_provider:
            entity:
                class: AppBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            logout_on_user_change: true
            pattern: ^/
            provider: pokeshop_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: after_login_route_name
            remember_me:
                secret:   '%secret%'
                lifetime: 86400 # 1 day in seconds
                path:     /
            logout:
                path:   /logout
                target: /


    role_hierarchy:
        ROLE_ADMIN: ROLE_USER


    access_control:
        - { path: ^/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }


    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt