security:

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            logout_on_user_change: true

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext